# Generated by Django 4.0.5 on 2022-06-07 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ticker', models.CharField(max_length=10)),
                ('buyDate', models.CharField(max_length=10)),
                ('sellDate', models.CharField(max_length=10)),
                ('percentChange', models.DecimalField(decimal_places=2, max_digits=19)),
                ('graph', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
