# Generated by Django 4.0.5 on 2022-06-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hex',
            field=models.CharField(default='trials', max_length=32),
            preserve_default=False,
        ),
    ]
